In [1]:
spam = 1

In [2]:
text = "I am revising my python basics again."

In [3]:
text

'I am revising my python basics again.'

In [4]:
spam

1

In [5]:
2 + 2

4

In [6]:
50 - 5*6


20

In [7]:
(50 - 5*6) / 4

5.0

In [8]:
8 / 4

2.0

In [9]:
17 / 3


5.666666666666667

In [10]:
17 // 3

5

In [11]:
17 % 3

2

In [12]:
5 * 3 -2

13

In [13]:
5 ** 2

25

In [14]:
2 ** 7

128

In [15]:
width = 20
height = 5 * 9
width * height

900

In [16]:
n

NameError: name 'n' is not defined

In [ ]:
4 * 1.3 - 1

In [ ]:
tax = 12.5 / 100

In [ ]:
price = 100.50

In [ ]:
price * tax

In [ ]:
price + _

In [ ]:
round(_, 2)

In [ ]:
'spam eggs'

In [ ]:
'doesn\'t'

In [ ]:
"doesn't"

In [ ]:
'"Yes," he said'

In [ ]:
"\"Yes\", he said"

In [ ]:
'"Isn\'t" she said.'

In [ ]:
print('Isn\'t, she said.')

In [ ]:
print('C:\some\name')

In [ ]:
print(r'C:\some\name')

In [ ]:
print("""
This is a multiline 
comment and so it will print 
on three lines.
""")

In [ ]:
3 * 'un' + 'ium'

In [ ]:
'Py' 'thon'

In [ ]:
prefix = 'Py'

In [ ]:
prefix 'thon'

In [ ]:
prefix + 'thon'

In [ ]:
text = ('This is line one'
       'This is line two')

In [ ]:
text

In [ ]:
word = 'Python'

In [ ]:
word[0]

In [ ]:
word[5]

In [ ]:
word[-1]

In [ ]:
word[-2]

In [ ]:
word[-6]

In [ ]:
word[0:2]

In [ ]:
word[2:5]

In [ ]:
word[:2] + word[2:]

In [ ]:
word[-2:]

In [ ]:
word[9]

In [ ]:
word[2:99]

In [ ]:
word[0] = 'J'

In [ ]:
'J' + word[1:]

In [ ]:
word[:2] + 'Py'

In [ ]:
someWord = 'BigWord'

In [ ]:
len(someWord)

In [ ]:
squares = [1, 4, 9, 16, 25]

In [ ]:
squares


In [ ]:
squares[0]

In [ ]:
squares[len(squares) - 1]

In [ ]:
squares[-1]

In [ ]:
squares[-3:]

In [ ]:
squares[:]

In [ ]:
squares + [36, 49, 64, 81, 100]

In [ ]:
squares

In [ ]:
cubes = [1, 8, 27, 65, 125]

In [ ]:
4 ** 3

In [ ]:
cubes[3]

In [ ]:
cubes

In [ ]:
cubes.append(216)

In [ ]:
cubes.append(7 ** 3)

In [ ]:
cubes

In [ ]:
letters = ['a','b','c','d','e','f','g']

In [ ]:
letters


In [ ]:
letters[2:5] = ['C','D','E']

In [ ]:
letters

In [ ]:
letters[2:5] = []

In [ ]:
letters

In [ ]:
letters = []

In [ ]:
letters


In [ ]:
letters = ['a','b','c','d','e','f','g']

In [ ]:
len(letters)

In [ ]:
a = ['a', 'b', 'c']
n = [1, 2, 3]
x = [a, n]

In [ ]:
x

In [ ]:
x[0]

In [ ]:
x[1]

In [ ]:
x[0][2]

In [ ]:
a, b = 0, 1
while b < 10:
    print(b, end=',')
    a, b = b, a+b

In [ ]:
i = 256*256
print('The value of i is ',i)

In [ ]:
x = int(input("Please enter an integer: "))

In [ ]:
if x < 0:
    x = 0
    print('Negative changed to zero')
elif x == 0:
    print('Zero')
elif x == 1:
    print('Single')
else:
    print('More')

In [ ]:
words = ['cat', 'window', 'sitting']

In [ ]:
for w in words:
    print(w, len(w))

In [ ]:
for w in words[:]:
    if len(w) > 6:
        words.insert(0, w)

In [ ]:
words

In [ ]:
len('sitting')

In [ ]:
for i in range(10, 20, 2):
    print(i)

In [ ]:
for i in range(-10, -100, -5):
    print(i)

In [ ]:
a = ['Mary',
     'had',
     'a',
     'little',
     'lamb'
    ]

In [ ]:
for i in range(len(a)):
    print(i, a[i])

In [ ]:
print(range(10))

In [ ]:
list(range(0,5))

In [ ]:
for n in range(2, 10):
    for x in range(1, n):
        if n% x == 0:
            print(n, 'equals', x, '*', n//x)
            break
        else:
            print(n ,'is a prime number')

In [ ]:
for num in range(2, 10):
    if num % 2 == 0 :
        print('Found an even number:', num)
        continue
    print("Found a number", num)

In [ ]:
while True:
    pass

In [ ]:
class MyEmptyClass:
    pass

In [ ]:
def initlog(*args):
    pass

In [ ]:
def fib(n):
    a, b = 0, 1
    while a< n:
        print(a, end=" ")
        a, b =b, a+b
    print()

In [ ]:
fib(3)

In [ ]:
fib

In [ ]:
f= fib

In [ ]:
f(100)

In [ ]:
fib(0)

In [ ]:
print(fib(0))

In [ ]:
def fib2(n):
    result = []
    a, b = 0, 1
    while a < n:
        result.append(a)
        a, b =b, a+b
    return result

    

In [ ]:
f100 = fib2(100)

In [ ]:
f100

In [ ]:
def ask_ok(prompt, retries=4, reminder ='Please try again!'):
    while True:
        ok = input('prompt')
        if ok in ('y','ye','yes'):
            return True
        if ok in ('n', 'no', 'nop', 'nope'):
            return False
        retries = retries - 1
        if retries < 0:
            raise ValueError('invalid user response')
        print(reminder)

In [ ]:
ask_ok('Do you really want to quit?')

In [ ]:
ask_ok('Are you a champion?')

In [ ]:
i = 5

def f(arg=i):
    print(arg)
    
i = 6
f()

In [ ]:
def f(a, L=[]):
    L.append(a)
    return L

print(f(1))
print(f(2))
print(f(3))

In [ ]:
def f(a, L=None):
    if L is None:
        L = []
    L.append(a)
    return L

print(f(1))
print(f(2))
print(f(3))

In [ ]:
def parrot(voltage, action = 'Voom'):
    print("-- This parrot wouldn't", action, end=' ')

In [ ]:
parrot(1000)

In [ ]:
def function(a):
    pass


function(0, a=0)

In [ ]:
def cheeseshop(kind, *arguments, **keywords):
    print("Do you have any", kind, "?")
    for arg in arguments:
        print(arg)
    keys = sorted(keywords.keys())
    for kw in keys:
        print(kw, ":", keywords[kw])

In [ ]:
cheeseshop("Limburger", "It's very runny, sir.",
           "It's really very, VERY runny, sir.",
           shopkeeper="Michael Palin",
           client="John Cleese",
           sketch="Cheese Shop Sketch")

In [ ]:
def write_multiple_items(file, separator, *args):
    file.write_multiple_items(separator.join(args))

In [ ]:
def concat(*args, sep="/"):
    return sep.join(args)

In [ ]:
concat("earth", "mars", "venus")

In [ ]:
list(range(3, 6))

In [ ]:
args = [3, 6]

In [ ]:
list(range(*args))

In [ ]:
def make_incrementor(n):
    return lambda x: x + n

In [ ]:
f = make_incrementor(42)

In [ ]:
f(0)

In [ ]:
f(1)

In [ ]:
pairs = [(1, 'one'),(2, 'two'),(3, 'three')]

In [ ]:
pairs.sort(key=lambda pair : pair[1])

In [ ]:
pairs

In [ ]:
def my_funtion():
    """
    Do nothing, but document it.
    
    No, really, it doesn't do anything.
    """
    pass


In [ ]:
print(my_funtion.__doc__)

In [ ]:
def f(ham: str, eggs: str = 'eggs') -> str:
    print("Annotations:", f.__annotations__)
    print("Arguments:", ham, eggs)
    return ham + 'and' + eggs

In [ ]:
f('spam')

In [ ]:
fruits  = ['ornage', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']

In [ ]:
fruits.count('apple')

In [ ]:
fruits.count('banana')

In [ ]:
fruits.index('apple',3)

In [ ]:
fruits.reverse()

In [ ]:
fruits

In [ ]:
fruits.append('grape')

In [ ]:
fruits

In [ ]:
fruits.sort()

In [ ]:
fruits

In [ ]:
fruits.pop()

In [ ]:
fruits

In [ ]:
stack = [3, 4, 5]

In [ ]:
stack.append(6)

In [ ]:
stack

In [ ]:
stack.pop()

In [ ]:
stack

In [ ]:
from collections import deque
queue = deque(["Eric", "John", "Michael"])
queue.append("Terry")
queue.append("Grahan")

In [ ]:
queue

In [ ]:
queue.popleft()

In [ ]:
queue.popleft()

In [ ]:
queue

In [ ]:
squares = []
for x in range(10):
    squares.append(x **2)

In [ ]:
squares


In [ ]:
squares = [x ** 2 for x in range(10)]

In [ ]:
squares

In [ ]:
[(x, y) for x in [1, 2, 3] for y in [3, 1, 4] if x != y]

In [ ]:
vec = [-4, -2, 0, 2, 4]

In [ ]:
[x*2 for x in vec]

In [ ]:
[p for p in vec if p >= 2]

In [ ]:
[abs(x) for x in vec]

In [ ]:
freshfruit = [' banana',' loganberry','passion fruit']

In [ ]:
[weapon.strip() for weapon in freshfruit]

In [ ]:
[(x, x**2) for x in range(3)]

In [ ]:
vec  = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
[num for elem in vec for num in elem ]

In [ ]:
from math import pi

In [ ]:
[str(round(pi, i)) for i in range(1, 6)]

In [ ]:
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
]

In [ ]:
[[row[i] for row in matrix] for i in range(4)]

In [ ]:
transposed = []
for i in range(4):
    transposed.append([row[i] for row in matrix])

In [ ]:
transposed

In [ ]:

a =[ -1, 0, 1]

In [ ]:
del a[0]

In [ ]:
a

In [ ]:
a= [1, 2, 3,4 ]

In [ ]:
del a[2:]

In [ ]:
a

In [ ]:
del a[:]

In [ ]:
a

In [ ]:
t = 1234, 12313, 'Hello!'

In [ ]:
t[0]

In [ ]:
t

In [ ]:
u = t, (1,2,3,4,5)

In [ ]:
u

In [ ]:
t[0] = 213

In [ ]:
v= ([1,2,3], [4,5,6])

In [ ]:
v

In [ ]:
empty = ()

In [ ]:
singleton = 'hello',

In [ ]:
len(empty)

In [ ]:
len(singleton)

In [ ]:
singleton

In [ ]:
x, y, z = t

In [ ]:
x

In [ ]:
y

In [ ]:
z

In [ ]:
basket = {'apple', 'orange','apple', 'pear', 'orange','banana'}

In [ ]:
print(basket)

In [ ]:
'orange' in basket

In [ ]:
'peaches' in basket

In [ ]:
a= set('dasdasda')

In [ ]:
b= set('asdasda')

In [ ]:
a

In [ ]:
a - b

In [ ]:
a | b

In [ ]:
a & b

In [ ]:
a ^ b

In [ ]:
a= {x for x in 'sadasdasdvc' if x not in 'sdas'}

In [ ]:
a

In [ ]:
tel = { 'jack': 123, 'sape' : 23123}

In [ ]:
tel['jack']

In [ ]:
tel['rittick'] = 1

In [ ]:
del tel['sape']

In [ ]:
tel

In [ ]:
list(tel.keys())

In [ ]:
sorted(tel.keys())

In [ ]:
'rittick' in tel

In [ ]:
'jack' not in tel

In [ ]:
dict([('rittick', 1), ('datta', 1)])

In [ ]:
{x : x**2 for x in (2, 4, 6)}

In [ ]:
dict(rittick = 123, robin = 456)

In [ ]:
knights = {'gallahad': 'the pure', 'robin':'the brave'}

In [ ]:
for k, v in knights.items():
    print(k, v)

In [ ]:
for i,v in enumerate(['tic', 'tac', 'toe']):
    print(i, v)

In [ ]:
questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']

In [ ]:
for q, a in zip(questions, answers):
    print('What is your {0}? It is {1}'.format(q,a))

In [ ]:
for i in reversed(range(1, 10, 2)):
    print(i)

In [ ]:
basket = [ 'orange', 'pear', 'apple']

In [ ]:
for f in sorted(set(basket)):
    print(f)

In [ ]:
import math
raw_data = [56.2, float('NaN'), 51.7, 55.6,65.8]

In [ ]:
filtered_data = []
for value in raw_data:
    if not math.isnan(value):
        filtered_data.append(value)

In [ ]:
filtered_data

In [ ]:
str1, str2, str3 = '', 'Trodneim', 'Hammer Dance'

In [ ]:
non_null = str1 or str2 or str3

In [ ]:
non_null

In [ ]:
(1, 2, 3) < (1, 2, 4)

In [ ]:
[1, 2, 3] < [1, 2, 4]

In [ ]:
'ABC' < 'C' < 'Pascal' < 'Python'

In [ ]:
(1,2,3,4) < (1, 2, 4)

In [ ]:
(1, 2) < (1, 2, -1)

In [ ]:
from fibo import *

In [ ]:
import sys


In [ ]:
sys.ps1

In [ ]:
sys.ps2

In [ ]:
dir(sys)

In [ ]:
dir()

In [ ]:
import builtins

In [ ]:
dir(builtins)

In [ ]:
s = 'Hello World.'

In [ ]:
str(s)

In [ ]:
repr(s)

In [ ]:
for x in range(1, 11):
    print(repr(x).rjust(2), repr(x*x).rjust(3), end=' ')
    print(repr(x*x*x).rjust(4))

In [ ]:
'12'.zfill(4)

In [ ]:
'-3.14'.zfill(7)

In [ ]:
print('We are the {} who say {}'.format('knights', 'Ni'))

In [ ]:
print('{} and {}'.format('spam', 'eggs'))

In [ ]:
print('{1} and {0}'.format('spam', 'eggs'))

In [ ]:
print('This {food} is absolutely {adjective}'.format(food = 'spam', adjective='horrible'))

In [ ]:
print('The story of {0}, {1}, and the {other}'.format('Rittick', 'Alina', other='Sucker'))

In [ ]:
import math
print('The value of PI is approximately {0:.3f}.'.format(math.pi))

In [ ]:
table = {'Sjoerd': 4127, 'Jack': 4098, 'Dcab': 7678}
for name, phone in table.items():
    print('{0:10} ==> {1:10d}'.format(name, phone))

In [ ]:
print('Jack: {0[Jack]:d}; Sjoerd: {0[Sjoerd]:d}; Dcab: {0[Dcab]:d}'.format(table))

In [ ]:
f = open('workfile.txt', 'w')

In [ ]:
f.write('This is line one.')

In [ ]:
f.close()

In [ ]:
f= open('workfile.txt','r')

In [ ]:
f.read()

In [ ]:
for line in f:
    print(line, end='')

In [ ]:
f.readline()

In [ ]:
value = ('the answer', 42)
s=str(value)

In [ ]:
f.write(s)

In [ ]:
with open('workfile.txt', 'r') as f:
    read_data = f.read()

In [ ]:
f.closed

In [ ]:
import json
json.dumps([1, 'simple','list'])

In [ ]:
f = open('workfile.txt', 'w')

In [ ]:
json.dump([1, 2, 'Hi'], f)

In [ ]:
f.close()

In [ ]:
f = open('workfile.txt','r')

In [ ]:
x = json.load(f)

In [ ]:
x

In [ ]:
10 * (1/0)

In [ ]:
while True:
    try:
        x = int(input("Please enter a number: "))
        break
    except ValueError:
        print("Oops! That was no valid number. Try again...")

In [ ]:
import sys

try:
    f = open('workfile.txt')
    s= f.readline()
    i =int(s.strip())
except OSError as err:
    print("OS Error: {0}".format(err))
except ValueError:
    print("Could not convert data to an integer.")
except:
    print("Unexpected error: ", sys.exe_info()[0])
    raise

In [ ]:
def this_fails():
    x = 1/0

In [ ]:
try:
    this_fails()
except ZeroDivisionError as err:
    print('Handling run-time error:', err)

In [ ]:
raise NameError('HiThere')

In [ ]:
raise ValueError

In [ ]:
def divide(x, y):
    try:
        result = x/y
    except ZeroDivisionError:
        print("Division by zero!")
    else:
        print("result is", result)
    finally:
        print("executing finally clause")

In [ ]:
divide(2, 1)

In [ ]:
divide(2,0)

In [ ]:
def scope_test():
    def do_local():
        spam = "local spam"
        
    def do_nonlocal():
        nonlocal spam
        spam ="nonlocal spam"
        
    def do_global():
        global spam
        spam = "global spam"
        
    spam ="test spam"
    do_local()
    print("After local assignment:", spam)
    do_nonlocal()
    print("After nonlocal assignment:", spam)
    do_global()
    print("After global assignment:", spam)
    
scope_test()
print("In Global Scope:", spam)

In [ ]:
class MyClass:
    """A Simple Class Example"""
    i = 12345
    
    def f(self):
        return 'Hello World'
    

In [ ]:
def __init__(self):
    self.data = []

In [ ]:
class Complex:
    def __init__(self, realpart, imagpart ):
        self.r  = realpart
        self.i = imagpart
        

In [ ]:
x = Complex(12,-3.9)

In [ ]:
x.i

In [ ]:
x.r, x.i

In [ ]:
class dog:
    
    kind = 'canine'
    
    def __init__(self, name):
        self.name = name
        
        

In [ ]:
d= dog('Peggy')

In [ ]:
d.kind

In [ ]:
d.name


In [ ]:
e = dog('Tazo')

In [ ]:
e.kind, e.name

In [ ]:
class Dog:
    
    
    
    def __init__(self, name):
        self.name = name
        self.tricks = []
        
    def add_trick(self, trick):
        self.tricks.append(trick)

In [ ]:
d = Dog('Frido')

In [ ]:
d.add_trick('Roll Over')

In [ ]:
d.tricks

In [ ]:
def f1(self, x, y):
    return min(x, x+y)

class C:
    
    f=f1
    
    def g(self):
        return 'Hello World'
    
    h =g

In [ ]:
x = C()

In [ ]:
x.f(1,2)

In [ ]:
x.h()

In [ ]:
class Bag:
    
    def __init__(self):
        self.data = []
        
    def addData(self, x):
        self.data.append(x)
        
        

In [ ]:
obj = Bag()

In [ ]:
obj.addData(1)

In [ ]:
obj.data

In [ ]:
class Mapping:
    pass

In [ ]:
class MappingsSubClass(Mapping):
    pass

In [ ]:

class Employee:
    pass

In [ ]:
john = Employee()

In [ ]:
john.name = 'John Doe'

In [17]:
john.dept = 'Computers'

NameError: name 'john' is not defined

In [ ]:
john.salary = 100000

In [ ]:
john.dept

In [ ]:
for element in (1, 2, 3):
    print(element)

In [ ]:
s = 'abc'
it =iter(s)

In [ ]:
it

In [ ]:
next(it)

In [ ]:
next(it)

In [ ]:
def reverse(data):
    for index in range(len(data)-1, -1, -1):
        yield data[index]

In [ ]:
for char in reverse('flog'):
    print(char)

In [ ]:
sum(i*i for i in range(10))

In [ ]:
xvec = [10, 20, 30]

In [ ]:
yvec =[7, 5, 3]

In [ ]:
sum(x*y for x, y in zip(xvec, yvec))

In [ ]:
set(word for line in page for word in line.split())

In [ ]:
data ='golf'
list(data[i] for i in range(len(data)-1, -1, -1))

In [ ]:
import os

In [ ]:
os.getcwd()

In [ ]:
dir(os)

In [ ]:
help(os)

In [ ]:
import shutil

In [ ]:
import glob

In [ ]:
glob.glob('*.py')

In [ ]:
import sys
print(sys.argv)

In [ ]:
import re

In [ ]:
re.findall(r'\bf[a-z]*', 'which foot or hand fell fastest')

In [ ]:
'tea for too'.replace('too', 'two')

In [ ]:
import math

In [ ]:
math.log(1024,2)

In [ ]:
import random

In [ ]:
random.choice(['apple','orange','banana'])

In [ ]:
random.random()

In [ ]:
random.sample(range(100),10)

In [ ]:
random.randrange(5)

In [ ]:
import statistics

In [ ]:
data = [1,2,3,4,5.5]

In [ ]:
statistics.mean(data)

In [ ]:
statistics.median(data)

In [ ]:
statistics.variance(data)

In [ ]:
from urllib.request import urlopen

In [ ]:
with urlopen('http://tycho.usno.navy.mil/cgi-bin/timer.pl') as response:
    for line in response:
        line = line.decode('utf-8')
        if 'EST' in line or 'EDT' in line:
            print(line)

In [ ]:
import smtplib

In [ ]:
server = smtplib.SMTP('localhost')

In [ ]:
from datetime import date
now = date.today()

In [ ]:
now

In [ ]:
birthday = date(1990, 12, 14)
age = now - birthday


In [ ]:
age.days

In [ ]:
9667/365


In [ ]:
import zlib

In [ ]:
s = b'witch which has which witches wrist watch'

In [ ]:
len(s)

In [ ]:
t= zlib.compress(s)

In [ ]:
len(t)

In [ ]:
zlib.decompress(t)

In [ ]:
zlib.crc32(s)

In [ ]:
from timeit import Timer
Timer('t=a; a=b; b=t','a=1; b=2').timeit()

In [ ]:
def average(values):
    """
    >>> print(average([20,30,70]))
    40.0
    """
    return sum(values)/len(values)

import doctest
doctest.testmod()

In [ ]:
import unittest

In [ ]:
import logging

In [ ]:
logging.

In [ ]:
from array import array

In [ ]:
sum(array('H', [1,2,3]))

In [ ]:
import numpy as np

In [ ]:
a = np.arange(15).reshape(3, 5)

In [ ]:
a

In [ ]:
a.shape

In [ ]:
a.ndim

In [ ]:
a.dtype.name

In [ ]:

a.size

In [ ]:

type(a)

In [ ]:
b = np.array([1,2,3])

In [ ]:
b

In [ ]:
type(b)

In [ ]:
np.array([(1,2,3),(4,5,6)])

In [ ]:
np.array([[1,2],[3,4]], dtype=complex)

In [ ]:
np.zeros((2,3))

In [ ]:
np.ones((2,3,4), dtype=np.int32)

In [ ]:
np.empty((2,3))

In [ ]:
np.arange(10, 20,2)

In [ ]:
np.arange(0,1,.01)

In [ ]:
from numpy import pi

In [ ]:
np.linspace(0, 2, 9)

In [ ]:
x = np.linspace(0, 2*pi, 100)

In [ ]:
f = np.sin(x)

In [ ]:
f

In [ ]:
a= np.arange(10)

In [ ]:
print(a)

In [ ]:
b = np.arange(10).reshape(2, 5)

In [ ]:
print(b)

In [ ]:
c = np.arange(24).reshape(2, 3, 4)

In [ ]:
print(c)

In [ ]:
print(np.arange(10000))

In [ ]:
print(np.arange(1000).reshape(10*100))

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
b = np.arange(4)

In [ ]:
b

In [ ]:
c = a - b

In [ ]:
c

In [ ]:
b**2

In [ ]:
b

In [ ]:
10*np.sin(a)

In [ ]:
a<-1

In [ ]:
A = np.array([[1,1],
             [0,1]])

In [ ]:
B = np.array([[2,0],
             [3,4]])

In [ ]:
A*B


In [ ]:
A.dot(B)

In [ ]:
np.dot(A,B)

In [ ]:
a = np.ones((2,3), dtype=int)

In [ ]:
b = np.random.random((2,3))

In [ ]:
a *= 3

In [ ]:
a

In [ ]:
b += a

In [ ]:
b

In [ ]:
a += b

In [ ]:
np.exp(a*10)

In [ ]:
a = np.random.random((2,3))

In [ ]:
a

In [ ]:
a.sum()

In [ ]:
a.min()

In [ ]:
a.max()

In [ ]:
n = np.arange(12).reshape(3,4)

In [ ]:
b

In [ ]:
n

In [ ]:
n.sum(axis=0)

In [ ]:
n.sum(axis=1)

In [ ]:
n.min(axis=0)

In [ ]:
n

In [ ]:
n.min(axis=1)

In [ ]:
n.cumsum(axis=0)

In [ ]:
n.cumsum(axis=1)

In [ ]:
B = np.arange(3)

In [ ]:
B

In [ ]:
np.exp(B)

In [ ]:
np.sqrt(B)

In [ ]:
a = np.arange(10)**3

In [ ]:
a

In [ ]:
a[2]

In [ ]:
a[2:4]

In [ ]:
a[0:6:2] = -1000

In [ ]:
a

In [ ]:
a[: : -1]

In [ ]:
for i in a:
    print(i**(1/3.))

In [ ]:
def f(x, y):
    return 10*x+y

In [ ]:
b = np.fromfunction(f, (5,4),dtype=int)

In [ ]:
b

In [ ]:
b[2,3]

In [ ]:
b[0:5, 1]

In [ ]:
b[:,1]

In [ ]:
b[1:3,:]

In [ ]:
b[-1]

In [ ]:
for element in B.flat:
    print(element)

In [ ]:
a

In [ ]:
A

In [ ]:
A.ravel()

In [ ]:
A.shape =(2,2)

In [ ]:
A.T

In [ ]:
A.shape = (1,4)

In [ ]:
A.T

In [ ]:
A

In [ ]:
A.resize((4,1))

In [ ]:
A

In [ ]:
A.reshape(2,-1)

In [ ]:
a = np.floor(10*np.random.random((2,2)))

In [ ]:
 b = np.floor(10*np.random.random((2,2)))

In [ ]:
np.vstack((a,b))

In [ ]:
np.hstack((a,b))

In [19]:
import numpy as np
a= np.floor(10*np.random.random((2,12)))

In [20]:
a

array([[ 3.,  4.,  0.,  0.,  7.,  3.,  5.,  5.,  5.,  5.,  6.,  8.],
       [ 7.,  6.,  0.,  2.,  0.,  9.,  6.,  0.,  7.,  3.,  0.,  8.]])

In [21]:
np.hsplit(a,3)

[array([[ 3.,  4.,  0.,  0.],
        [ 7.,  6.,  0.,  2.]]), array([[ 7.,  3.,  5.,  5.],
        [ 0.,  9.,  6.,  0.]]), array([[ 5.,  5.,  6.,  8.],
        [ 7.,  3.,  0.,  8.]])]

In [22]:
np.hsplit(a, (3,4))

[array([[ 3.,  4.,  0.],
        [ 7.,  6.,  0.]]), array([[ 0.],
        [ 2.]]), array([[ 7.,  3.,  5.,  5.,  5.,  5.,  6.,  8.],
        [ 0.,  9.,  6.,  0.,  7.,  3.,  0.,  8.]])]

In [23]:
a = np.arange(12)

In [24]:
b = a

In [25]:
b is a

True

In [26]:
b.shape = 3,4

In [27]:
a.shape

(3, 4)

In [28]:
def f(x):
    print(id(x))

In [29]:
id(a)

92221648

In [30]:
f(a)

92221648


In [31]:
c =a.view()

In [32]:
c is  a

False

In [33]:
c.base is a

True

In [34]:
c.flags.owndata

False

In [35]:
c.shape = 2,6

In [36]:
a.shape

(3, 4)

In [37]:
c[0,4] = 1234

In [38]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [40]:
s = a[:, 1:3]

In [41]:
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [42]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [43]:
d = a.copy()

In [44]:
d is a

False

In [45]:
d.base is a

False

In [46]:
d[0,0]

0

In [47]:
d[0,0] = 999

In [48]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [53]:
a=  np.arange(12)**2

In [54]:
i = np.array([1,1,3,8,5])

In [55]:
a[i]

array([ 1,  1,  9, 64, 25])

In [56]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [57]:
j = np.array([[3,4],[9,7]])

In [58]:
a[j]

array([[ 9, 16],
       [81, 49]])

In [59]:
a = np.arange(12).reshape((3,4))

In [60]:
b = a > 4

In [61]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [62]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [63]:
a[b] = -1

In [64]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [65]:
a= np.array([[1.0,2.0],[3.0,4.0]])

In [66]:
print(a)

[[ 1.  2.]
 [ 3.  4.]]


In [67]:
a.transpose()

array([[ 1.,  3.],
       [ 2.,  4.]])

In [68]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [69]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [70]:
a, b = 1, 2

In [71]:
a

1

In [72]:
b

2

In [6]:
import numpy as np
v= np.random.normal(2, 0.5, 10000)

In [7]:
import matplotlib.pyplot as plt

In [8]:
plt.hist(v, bins = 50, normed=1)

(array([ 0.00426013,  0.00426013,  0.01136035,  0.00852026,  0.01846056,
         0.02982091,  0.02698082,  0.05396165,  0.07242221,  0.08662264,
         0.14484442,  0.15762481,  0.23146706,  0.24424745,  0.36211104,
         0.37631147,  0.46293411,  0.4984352 ,  0.63191927,  0.66458026,
         0.69014104,  0.72848221,  0.74268264,  0.82362511,  0.76966347,
         0.7938042 ,  0.71712186,  0.70718156,  0.66742035,  0.64043953,
         0.53393628,  0.49133498,  0.36353108,  0.35217074,  0.25702784,
         0.23572719,  0.16330498,  0.11218342,  0.08378255,  0.06816208,
         0.05680173,  0.03692113,  0.01846056,  0.01988061,  0.00852026,
         0.01136035,  0.00710022,  0.00284009,  0.00426013,  0.00142004]),
 array([ 0.30743485,  0.37785524,  0.44827563,  0.51869602,  0.58911641,
         0.65953679,  0.72995718,  0.80037757,  0.87079796,  0.94121835,
         1.01163873,  1.08205912,  1.15247951,  1.2228999 ,  1.29332029,
         1.36374068,  1.43416106,  1.50458145,  1

In [9]:
plt.show()