In [1]:
import numpy as np

In [2]:
import matplotlib as mpl


In [3]:
import matplotlib.pyplot as plt

In [4]:
from scipy import linalg, optimize

In [5]:
np.info(optimize.fmin)

 fmin(func, x0, args=(), xtol=0.0001, ftol=0.0001, maxiter=None, maxfun=None,
      full_output=0, disp=1, retall=0, callback=None)

Minimize a function using the downhill simplex algorithm.

This algorithm only uses function values, not derivatives or second
derivatives.

Parameters
----------
func : callable func(x,*args)
    The objective function to be minimized.
x0 : ndarray
    Initial guess.
args : tuple, optional
    Extra arguments passed to func, i.e. ``f(x,*args)``.
callback : callable, optional
    Called after each iteration, as callback(xk), where xk is the
    current parameter vector.
xtol : float, optional
    Relative error in xopt acceptable for convergence.
ftol : number, optional
    Relative error in func(xopt) acceptable for convergence.
maxiter : int, optional
    Maximum number of iterations to perform.
maxfun : number, optional
    Maximum number of function evaluations to make.
full_output : bool, optional
    Set to True if fopt and warnflag outputs are desi

In [8]:
dir()

['In',
 'Out',
 '_',
 '_7',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i2',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 '_sh',
 'exit',
 'get_ipython',
 'linalg',
 'mpl',
 'np',
 'optimize',
 'plt',
 'quit']

In [9]:
a = np.r_[3,[0]*5]

In [10]:
a

array([3, 0, 0, 0, 0, 0])

In [11]:
np.mgrid[0:5,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [12]:
from numpy import poly1d

In [13]:
p = poly1d([3, 4, 5])

In [14]:
print(p)

   2
3 x + 4 x + 5


In [16]:
print(p*p)

   4      3      2
9 x + 24 x + 46 x + 40 x + 25


In [18]:
print(p.deriv())


 
6 x + 4


In [19]:
def addsubtract(a, b):
    if a > b:
        return a - b
    else:
        return a + b

In [20]:
addsubtract(1,2)

3

In [21]:
vec_addsubtract = np.vectorize(addsubtract)

In [30]:
vec_addsubtract([1,2,3],[3,2,1])

array([4, 4, 2])